name: Trigger auto deployment for javatestingapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/javatestingapp-AutoDeployTrigger-f287fbee-609e-46d8-a443-fb3e9b865b68.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.JAVATESTINGAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: shenregistry123.azurecr.io
          registryUsername: ${{ secrets.JAVATESTINGAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAVATESTINGAPP_REGISTRY_PASSWORD }}
          containerAppName: javatestingapp
          resourceGroup: shenrg
          imageToBuild: shenregistry123.azurecr.io/javatestingapp:${{ github.sha }}
          
            

     

